baseurl = "https://www.devforfoods.com/"
title = "iamminster"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Minh Nguyen"
    description = "Minh Nguyen's personal website"
    keywords = "blog,developer,personal"
    info = "Backend Engineer"
    avatarurl = "images/kumamon.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = true
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/iamminster/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/iamminster/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "https://iamminster.blogspot.com/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.ja]
        languagename = "Japanese"
        title = "iamminster"

        [languages.ja.params]
            author = "グエン・ミン"
            info = "バックエンドエンジニア"
            description = ""
            keywords = ""
            footercontent = ""

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "私について"
            weight = 1
            url = "about/"

            [[languages.ja.menu.main]]
            name = "ブログ"
            weight = 2
            url = "https://iamminster.blogspot.com/"

            [[languages.ja.menu.main]]
            name = "お問い合わせ"
            weight = 5
            url = "contact/"
